date : '20230106'

module:
  data_preprocess : True
  run_model : True

model:
  input_file_location : 'output.csv'

data_preprocess:
  time_window : 60


sniffer_list :
  - sniffer_zero
  - sniffer_one
  - sniffer_two
  - sniffer_three
  - sniffer_four
  - sniffer_five
  - sniffer_six


mobile_list :
  uu : '0000ce9c-0000-1000-8000-00805f9b34fb'
  u19e : '0000f22e-0000-1000-8000-00805f9b34fb'
  v4445 : '0000dd9b-0000-1000-8000-00805f9b34fb'
  a42 : '0000ccb5-0000-1000-8000-00805f9b34fb'

relation :
 - [0, 'v4445', 'uu']
 - [0, 'uu', 'v4445']

 - [2, 'a42', 'uu']
 - [2, 'a42', 'u19e'] 
 - [2, 'a42', 'v4445']
 - [2, 'uu', 'a42']
 - [2, 'u19e', 'a42'] 
 - [2, 'v4445', 'a42']

 - [1, 'u19e', 'uu']
 - [1, 'u19e', 'v4445']
 
 - [1, 'v4445', 'u19e']
 - [1, 'uu', 'u19e']

start_time :
  - "17:31:00"
  - "17:38:00"
  - "17:46:00"
  - "17:54:00"

end_time :
  - "17:36:00"
  - "17:43:00"
  - "17:51:00"
  - "17:59:00"